### PR TITLE
[WIP] Add dock for vHost

### PR DESCRIPTION
**Pull request by vk-en**
vHost configuration documentation in EVE

### CODE REVIEW

**Review by rvs — CHANGES_REQUESTED** [review]
Great first cut at the doc. Two tiny nits before this can be merged:
  * please take care of Yetus suggestions
  * can you please rename it to VHOST.md
?

**Comment by vk-en** [comment]
I renamed the file and added more information.

**Review by rvs — CHANGES_REQUESTED** [review]
Why is this coming to Eden instead of EVE?

**Comment by vk-en** [comment]
This guide is an intermediate result of work to understand the configuration vhost, and we thought that it makes no sense to add instructions for manually configuring vHost to the eve repository, because there it will and should be configured automatically.

I also think that while we have not yet decided on the use of vHost, it makes little sense to add manual configuration instructions to the main repository.

But if you think that it is necessary in eve too, then it won't be difficult for me to add it to EVE.

**Comment by mydatascience** [comment]
We have that in eve

**Comment by mydatascience** [comment]
We have

**Pull request closed without merging**
