### PR TITLE
[WIP - do not merge!!!] Fix something

### PR DESCRIPTION
**Pull request by christoph-zededa**

### CODE REVIEW

**Comment by christoph-zededa** [comment]
see https://github.com/lf-edge/eden/pull/976#issuecomment-2153515337

**Comment by christoph-zededa** [comment]
```
(ns: pillar) linuxkit-525400123456:/# ps auxww | grep dhcpcd
 2685 root      0:00 dhcpcd: eth1 [ip4] [ip6]
 2699 root      0:00 dhcpcd: eth0 [ip4] [ip6]
 4963 root      0:00 grep dhcpcd
(ns: pillar) linuxkit-525400123456:/# dhcpcd -U -4
no such user dhcpcd
dhcpcd is not running
```

there seems to be at least one false warning

**Comment by milan-zededa** [comment]
Are you seeing the same issue also when running the test locally or is it reproducible only on buildjet runners?

**Comment by christoph-zededa** [comment]
> Are you seeing the same issue also when running the test locally or is it reproducible only on buildjet runners?

I gave up trying to run it locally after it failed somewhere different.

**Comment by milan-zededa** [comment]
Closing this. The attempt to "Fix something" apparently failed :)

**Pull request closed without merging**
