### PR TITLE
newlog support

### PR DESCRIPTION
**Pull request by giggsoff**
Changes to support newlogs.

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Comment by mydatascience** [comment]
So when should we merge it?

**Comment by mydatascience** [comment]
Maybe we switch off log checks in Eden ?

**Comment by giggsoff** [comment]
@mydatascience @rvs we can merge it now

**Review by rvs — APPROVED** [review]
LGTM

**Pull request merged**
