### PR TITLE
Revert "Bump golang.org/x/net from 0.8.0 to 0.17.0 in /sdn/vm"

### PR DESCRIPTION
**Pull request by uncleDecart**
Reverts lf-edge/eden#904

Build fails, so we need to investigate what causes it

### CODE REVIEW

**Comment by uncleDecart** [comment]
@milan-zededa I guess we need to locally try to update it.

**Comment by uncleDecart** [comment]
@giggsoff can you check? :)

**Comment by giggsoff** [comment]
Can you please sign the commit?

**Comment by giggsoff** [comment]
Well, I think we can close it with https://github.com/lf-edge/eden/pull/904 merged.

**Comment by milan-zededa** [comment]
@giggsoff This is revert of #904, build started failing so we need to investigate and try update locally.

**Comment by uncleDecart** [comment]
@giggsoff can you please reopen it? I don't have permissions to do that

**Comment by uncleDecart** [comment]
Okay, now it seems to be working with two commits merged from dependabot

**Pull request closed without merging**
