### PR TITLE
GitHub Actions: adjust working directory in test.yml collect-info step

### PR DESCRIPTION
**Pull request by uncleDecart**
Following #898 we adjust collect-info working directory in new tests

### CODE REVIEW

**Review by milan-zededa — APPROVED** [review]

**Comment by giggsoff** [comment]
As I understood, `./eden` hardcoded in `collect-info` to not fill it from the caller side. We still have `./eden` as default. So do we really need the change?

**Comment by uncleDecart** [comment]
@giggsoff there's a problem with missing archive in new workflows https://github.com/lf-edge/eve/pull/3450 It might not be path, but has to be something

**Review by eriknordmark — APPROVED** [review]
LGTM

**Comment by giggsoff** [comment]
> @giggsoff there's a problem with missing archive in new workflows [lf-edge/eve#3450](https://github.com/lf-edge/eve/pull/3450) It might not be path, but has to be something

I still not sure that the problem is in path. Checked with added comment ` # created by collect-info action` to `eden.yml` workflow and looks like I hit the same [problem](https://github.com/giggsoff/eden/actions/runs/6421317160/job/17435392276?pr=47#step:15:16). May the problem be because of the [comment](https://github.com/lf-edge/eden/blob/a963693baa4fc5b0059d997ca89d0ac6f4cc50b2/.github/actions/publish-logs/action.yml#L50).

**Comment by uncleDecart** [comment]
I see that in case of EdenGCP workflow we have it and seems like difference is only in using github.working directory and this comment. I removed the comment and hope it'll fix things . And being explicit on workflow directory won't worsen it IMHO :)

**Comment by giggsoff** [comment]
Without explicit definition of working directory we use `./eden` (assume it is different before your change, my previous fix you mentioned in the description was about changing it because of difference) and as I can see in [discussion ](https://github.com/lf-edge/eve/pull/3450#issuecomment-1747278424)  it works, the action is able to find and run shell scripts to obtain required info. So why we should change the working directory if it works?

**Comment by uncleDecart** [comment]
@giggsoff in this discussion there's a problem that new workflows don't include this archive, two things which are different is using working directory and having this comment. In new workflows which we are calling from eve we are downloading eden and explicitly specifying working directory. My reasoning changing it here is because that way it's explicit. I'm not sure still how GHA are functioning, especially in scenario, where you call them from another repository. If you want, we can remove working directory and clean up comment and try it all together and if it works it's good. If not -- I'd specify working directory and run again

**Comment by uncleDecart** [comment]
@giggsoff removed the comment and workflow directories remain the same

**Review by giggsoff — APPROVED** [review]
Thank you, let it try!

**Pull request merged**
