### PR TITLE
Try to fix EdenGCP problems

### PR DESCRIPTION
**Pull request by giggsoff**
Two problems I try to avoid here:

- I can see problems with [network_test](https://github.com/lf-edge/eden/actions/runs/6407681780) on EdenGCP, seems they are resolved
- I can see that in case of xen we receive an IP with delay (the [first](https://github.com/itmo-eve/eden/actions/runs/6409594534/job/17401099093#step:17:7125) one, the [second](https://github.com/itmo-eve/eden/actions/runs/6409594534/job/17401099093#step:17:7188) one)

### CODE REVIEW

**Comment by uncleDecart** [comment]
Do we really need to bump sleep time in tests?

**Comment by giggsoff** [comment]
> Do we really need to bump sleep time in tests?

Well, if current one is not enough, and new one makes the test [green](https://github.com/itmo-eve/eden/actions/runs/6416013848/job/17418938228), why not?

**Comment by uncleDecart** [comment]
Can we try to make it in timeout? Like try to check every 10 second if operation is successful and if it is continue test. That way we it might save us some time in this test

**Comment by uncleDecart** [comment]
LGTM, thank you very much @giggsoff

**Review by uncleDecart — APPROVED** [review]

**Pull request merged**
