### PR TITLE
eden eve update

### PR DESCRIPTION
**Pull request by dautovri**
New command "eden eve update" proposed in https://github.com/lf-edge/eden/issues/622

Signed-off-by: Ruslan Dautov <dautov2@gmail.com>

### CODE REVIEW

**Comment by mydatascience** [comment]
Please add the documentation and description of usage here (like the screenshot of running the command)

**Comment by dautovri** [comment]
> Please add the documentation and description of usage here (like the screenshot of running the command)

```
 ./eden eve update
Error: accepts 1 arg(s), received 0
Usage:
  eden eve update <image file or url (oci:// or file:// or http(s)://)> [flags]

Flags:
  -h, --help   help for update

Global Flags:
      --config string      Name of config (default "default")
  -v, --verbosity string   Log level (debug, info, warn, error, fatal, panic (default "info")
```

Example of usage 

```
./eden eve version                                                                      
0.0.0-master-87f2a9a8-kvm-amd64
```
```
./eden eve update oci://docker.io/lfedge/eve:6.5.0-kvm-amd64
{"id":{"uuid":"ce4d5f77-b533-441e-bf37-702801217f82","version":"8"},"networks":[{"id":"6822e35f-c1b8-43ca-b344-0bbc0ece8cf1","type":4,"ip":{"dhcp":4,"dhcpRange":{}}},{"id":"6822e35f-c1b8-43ca-b344-0bbc0ece8cf2","type":4,"ip":{"dhcp":4,"dhcpRange":{}}}],"datastores":[{"id":"dadf645e-d4c8-4042-96d7-2d1348a6a7ed","dType":5,"fqdn":"docker://index.docker.io"}],"base":[{"uuidandversion":{"uuid":"3edd6ad1-cb7a-4d60-8ceb-99cb2ca9ea00","version":"4"},"drives":[{"image":{"uuidandversion":{"uuid":"3edd6ad1-cb7a-4d60-8ceb-99cb2ca9ea00","version":"1"},"name":"lfedge/eve:6.8.0-kvm-amd64","iformat":8,"dsId":"dadf645e-d4c8-4042-96d7-2d1348a6a7ed"}}],"baseOSVersion":"6.8.0-kvm-amd64"},{"uuidandversion":{"uuid":"b6e17eac-18c9-436e-a8dc-21c24af62afd","version":"4"},"drives":[{"image":{"uuidandversion":{"uuid":"b6e17eac-18c9-436e-a8dc-21c24af62afd","version":"1"},"name":"lfedge/eve:6.5.0-kvm-amd64","iformat":8,"dsId":"dadf645e-d4c8-4042-96d7-2d1348a6a7ed"}}],"baseOSVersion":"6.5.0-kvm-amd64"},{"uuidandversion":{"uuid":"5a3cde3d-5d1d-46aa-bc37-bdb7a132260a","version":"4"},"drives":[{"image":{"uuidandversion":{"uuid":"5a3cde3d-5d1d-46aa-bc37-bdb7a132260a","version":"1"},"name":"lfedge/eve:6.0.0-kvm-amd64","iformat":8,"dsId":"dadf645e-d4c8-4042-96d7-2d1348a6a7ed"}}],"activate":true,"baseOSVersion":"6.0.0-kvm-amd64"},{"uuidandversion":{"uuid":"b6e17eac-18c9-436e-a8dc-21c24af62afd","version":"4"},"drives":[{"image":{"uuidandversion":{"uuid":"b6e17eac-18c9-436e-a8dc-21c24af62afd","version":"1"},"name":"lfedge/eve:6.5.0-kvm-amd64","iformat":8,"dsId":"dadf645e-d4c8-4042-96d7-2d1348a6a7ed"}}],"baseOSVersion":"6.5.0-kvm-amd64"}],"reboot":{"counter":1000},"configItems":[{"key":"app.allow.vnc","value":"true"},{"key":"debug.default.loglevel","value":"info"},{"key":"debug.default.remote.loglevel","value":"warning"},{"key":"debug.enable.ssh","value":"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDa8APukdfWRMJ+8GhKCdMeEYmGRA0T5oXfqMrX+9JPX44JU2jMXplOurvqeR8dOzRpi9v/3n2vSSutb0RynKufn0V4Lt9V4nkg9k96YgO6p1CoOgNJTBIV6w+DsFJ9Dh6Tcsg+ysPetXB8CHujLLejoDxhfMZa2EbbL86ImITgR9gEG4D95B9+DLSen26VE2PyLkU4kuUBgMp6s3hHAQCrcPw55Mu09G2pgLXtEw9jTCun+N2CPgznhNZj8IPxY8F3NXkou9SacAhXdG/ms11n7aWc37rAPH3NHradbnhS0/j93ixE69NackhsfLAKGKnC5UrBndHLtdKFSMSmlPRMeSB9Pn1nVOayOLaRnr1iGKrXDvnwnzoZ1tbmQbveK2hwq/RmJf8q5uq7126khSbNMEmfEH9bAVovc2fQobOohlMlHNCnV7ILVF8qJM0IdYMgMUhkSwuWDleUePxQhSsIDQ3DGlBfUtc0tLJWI3uUzCLvaXPPnWROwCvsLgBfakKb/udhoH8GLoLZp51OEqkrGEWkficQK1/a+Qha7Vv/BHoFRueMdbYiBjkK59ktZkcD71HghicZM76A7ncQ9DQo+ym56Hb+YMmjmeTEVEKwAdKHbnElkccZam6xFOqd/g6ZxSLBlroLjQt6FHGKIqX6gYf5JGRlbsw7qD8gzkcX8w==\n"},{"key":"newlog.allow.fastupload","value":"true"},{"key":"timer.config.interval","value":"5"},{"key":"timer.metric.interval","value":"10"}],"systemAdapterList":[{"name":"eth0","uplink":true,"networkUUID":"6822e35f-c1b8-43ca-b344-0bbc0ece8cf1"},{"name":"eth1","networkUUID":"6822e35f-c1b8-43ca-b344-0bbc0ece8cf2"}],"deviceIoList":[{"ptype":1,"phylabel":"eth0","phyaddrs":{"Ifname":"eth0"},"logicallabel":"eth0","assigngrp":"eth0","usage":2,"usagePolicy":{"freeUplink":true}},{"ptype":1,"phylabel":"eth1","phyaddrs":{"Ifname":"eth1"},"logicallabel":"eth1","assigngrp":"eth1","usage":1,"usagePolicy":{"freeUplink":true}},{"ptype":2,"phylabel":"USB0:1","phyaddrs":{"UsbAddr":"0:1"},"logicallabel":"USB0:1","assigngrp":"USB0","usage":3},{"ptype":2,"phylabel":"USB0:2","phyaddrs":{"UsbAddr":"0:2"},"logicallabel":"USB0:2","assigngrp":"USB1","usage":3},{"ptype":2,"phylabel":"USB0:3","phyaddrs":{"UsbAddr":"0:3"},"logicallabel":"USB0:3","assigngrp":"USB2","usage":3},{"ptype":2,"phylabel":"USB1:1","phyaddrs":{"UsbAddr":"1:1"},"logicallabel":"USB1:1","assigngrp":"USB3","usage":3},{"ptype":2,"phylabel":"USB1:2","phyaddrs":{"UsbAddr":"1:2"},"logicallabel":"USB1:2","assigngrp":"USB4","usage":3},{"ptype":2,"phylabel":"USB1:3","phyaddrs":{"UsbAddr":"1:3"},"logicallabel":"USB1:3","assigngrp":"USB5","usage":3},{"ptype":2,"phylabel":"USB2:1","phyaddrs":{"UsbAddr":"2:1"},"logicallabel":"USB2:1","assigngrp":"USB6","usage":3},{"ptype":2,"phylabel":"USB2:2","phyaddrs":{"UsbAddr":"2:2"},"logicallabel":"USB2:2","assigngrp":"USB7","usage":3},{"ptype":2,"phylabel":"USB2:3","phyaddrs":{"UsbAddr":"2:3"},"logicallabel":"USB2:3","assigngrp":"USB8","usage":3},{"ptype":2,"phylabel":"USB3:1","phyaddrs":{"UsbAddr":"3:1"},"logicallabel":"USB3:1","assigngrp":"USB9","usage":3},{"ptype":2,"phylabel":"USB3:2","phyaddrs":{"UsbAddr":"3:2"},"logicallabel":"USB3:2","assigngrp":"USB10","usage":3},{"ptype":2,"phylabel":"USB3:3","phyaddrs":{"UsbAddr":"3:3"},"logicallabel":"USB3:3","assigngrp":"USB11","usage":3}],"productName":"ZedVirtual-4G"}
```
```
./eden eve version               
6.5.0-kvm-amd64
```

**Comment by mydatascience** [comment]
May we assume : 
   -  latest if no params 
   - dockerhub if we have only the version like: 
./eden eve update 6.5.0-kvm-amd64

**Comment by mydatascience** [comment]
Also will be cool if we can do: ./eden eve update 6.5.0 
kvm and amd64 derived from eden config

**Pull request merged**
