### PR TITLE
Try to disable kernel watchdog

### PR DESCRIPTION
**Pull request by milan-zededa**
Let's see if those kernel crashes will disappear...

### CODE REVIEW

**Comment by uncleDecart** [comment]
Fingers crossed

**Comment by giggsoff** [comment]
> Fingers crossed

Too much green to be true;)

**Comment by milan-zededa** [comment]
> > Fingers crossed
> 
> Too much green to be true;)

Yes, something does not add up :)

**Comment by milan-zededa** [comment]
Repeated test runs still show some kernel crashes :(

**Comment by uncleDecart** [comment]
> Repeated test runs still show some kernel crashes :(

That's more like it

**Comment by milan-zededa** [comment]
yes

**Pull request closed without merging**
