### PR TITLE
Model Intel NUC10i7FNH

### PR DESCRIPTION
**Pull request by all4innov**

### CODE REVIEW

**Review by eriknordmark — APPROVED** [review]
LGTM.
And welcome to EVE and Eden @all4innov all4innov

**Comment by mydatascience** [comment]
Please sign the commit @all4innov . And welcome )

**Comment by mydatascience** [comment]
@all4innov  could you please fix yetus and we are ready to accept

**Comment by mydatascience** [comment]
I will update yetus myself...

**Pull request merged**
