### PR TITLE
[WIP] Xen tests

### PR DESCRIPTION
**Pull request by giggsoff**

### CODE REVIEW

**Review by rvs — APPROVED** [review]
This looks reasonable @giggsoff -- however, can you please make sure to update https://github.com/lf-edge/eve/blob/master/.github/workflows/eden.yml so that our default run of PR validation includes some level of hypervisor testing?

Note, you don't have to add it IN ADDITION (like you're doing here) -- just make sure the default PR run on EVE is done with Xen and we're running PV apps.

**Comment by giggsoff** [comment]
The main problem here (for xen) is about 5 times more onboarding time and unpredictable time for other tests (actually, I can't pass the first one).

**Comment by rvs** [comment]
> The main problem here (for xen) is about 5 times more onboarding time and unpredictable time for other tests (actually, I can't pass the first one).

Are you disabling qemu acceleration by any chance?

**Comment by mydatascience** [comment]
Should we close this since we have GCP now?

**Comment by giggsoff** [comment]
#472

**Pull request closed without merging**
