### PR TITLE
Revert "Revert "userdata: add tests for write_files in containers""

### PR DESCRIPTION
**Pull request by uncleDecart**
Reverts lf-edge/eden#925

Since we bumped EVE version cloud-init test should work. This PR reverts the revert of PR :) 

image

### CODE REVIEW

**Comment by giggsoff** [comment]
Not sure that it is a blocker, but nice to see green mark of DCO [check](https://github.com/lf-edge/eden/pull/941/checks?check_run_id=20730525218).

**Comment by uncleDecart** [comment]
> Not sure that it is a blocker, but nice to see green mark of DCO [check](https://github.com/lf-edge/eden/pull/941/checks?check_run_id=20730525218).

Hmmm, I did this automatically, let me try to do some magic locally...

**Comment by uncleDecart** [comment]
@europaul I see some error [here](https://github.com/lf-edge/eden/actions/runs/7612911009/job/20731561440?pr=941#step:3:3012)

**Comment by europaul** [comment]
> @europaul I see some error [here](https://github.com/lf-edge/eden/actions/runs/7612911009/job/20731561440?pr=941#step:3:3012)

Thanks for noticing @uncleDecart . This is [off](https://github.com/lf-edge/eden/actions/runs/7612911009/job/20731561440?pr=941#step:3:8), I'm looking into it

**Comment by europaul** [comment]
let's see how the jobs run [here](https://github.com/lf-edge/eden/pull/942)

**Comment by uncleDecart** [comment]
force rebased to master. Let's see how it runs

**Comment by europaul** [comment]
@uncleDecart we can probably close this PR since it's now superseded by https://github.com/lf-edge/eden/pull/945

**Pull request closed without merging**
