### PR TITLE
New network tests

### PR DESCRIPTION
**Pull request by sadov**
Created universal `eclient` container with SSH access. Old network test split into two tests: simple `nc`-based client/server communication and `nginx` tests.

Signed-off-by: Oleg Sadov <oleg.sadov@gmail.com>

### CODE REVIEW

**Review by mydatascience — CHANGES_REQUESTED** [review]
We do not need this file at all 
These ports should be set by test user

**Comment by sadov** [comment]
Which file?

**Comment by mydatascience** [comment]
tests/eclient/eden+eclient.sh  

This one. This one adds port and restarts eden 

We require a user to explicitly define ports upon start of the test. We don't want start/stop eden within the test.

**Comment by sadov** [comment]
It will not stop/start `eden` if the ports are already set. We will need this script to run the test from scratch.

**Review by rvs — APPROVED** [review]
LGTM

**Pull request merged**
