### PR TITLE
Add model information for OnLogic MC510-50 (G5400T / 8G / 128G / TPM)

### PR DESCRIPTION
**Pull request by floucks**
@rvs 

Adding support for another model. A few questions to address:
* This device is configurable, so I've added the root model and the config in the name. There's no full model output SKU I can use so I've just included the config variables with assigned values in the template filename.
* The spec.sh always shows a bit smaller of a number for memory and disk...should I manually write those back up to their spec'd values? Or leave them as the script says? 

Thanks!

### CODE REVIEW

**Comment by floucks** [comment]
Looks like the Apache Yetus check failed due to invalid permissions:
~~~
ERROR: Failed to write github status. Token expired or missing repo:status write?
~~~

**Comment by kgiori** [comment]
@floucks -- yetus doesn't like the blank line at line 86 of your .json template file
`models/template_l1_OnLogic-MC510-50_P-G5400T_M-8G_D-128G_TPM.json:86:0:blanks:end of line`

That yetus complaint is also shown on the "Files Changed" tab of this pull request. Try removing that blank line and I bet it will pass.

**Comment by floucks** [comment]
Looks like we got it! Thanks @kgiori

**Comment by floucks** [comment]
@rvs @kgiori bumping this PR, looks like all tests have passed. Can you merge it and ask the ops team to push the template into my enterprise? Thank you.

**Review by rvs — APPROVED** [review]
LGTM

**Comment by rvs** [comment]
Thanks for contributing this @floucks -- as to "The spec.sh always shows a bit smaller of a number for memory and disk...should I manually write those back up to their spec'd values? Or leave them as the script says?" -- either way is fine actually. I merged as-is.

**Comment by floucks** [comment]
Thanks @rvs !!! My pleasure.

**Pull request merged**
