### PR TITLE
Remove deprecated packages

### PR DESCRIPTION
**Pull request by prnvkv-zededa**
The following packages/functions were deprecated in the repo and has been addressed:

- io/ioutil
- strings.Title
- rand.Seed
- github.com/golang/protobuf/proto

### CODE REVIEW

**Review by deitch — APPROVED** [review]
That is a lot of cleanup and modernization.

**Review by giggsoff — CHANGES_REQUESTED** [review]
It seems we should update base image we use to build go code after moving to new go version (for example I can see potential problem here https://github.com/lf-edge/eden/blob/master/Dockerfile, probably we can find other places with the same problem), can you please check?

**Comment by prnvkv-zededa** [comment]
> It seems we should update base image we use to build go code after moving to new go version (for example I can see potential problem here https://github.com/lf-edge/eden/blob/master/Dockerfile, probably we can find other places with the same problem), can you please check?

I ran `make build-docker` , `make build` and `make install` all ran successfully.  Is there any other way to verify this issue ?

**Comment by giggsoff** [comment]
> > It seems we should update base image we use to build go code after moving to new go version (for example I can see potential problem here https://github.com/lf-edge/eden/blob/master/Dockerfile, probably we can find other places with the same problem), can you please check?
> 
> I ran `make build-docker` , `make build` and `make install` all ran successfully. Is there any other way to verify this issue ?

It is `make build-docker`, sorry, it is not so obvious.

**Comment by prnvkv-zededa** [comment]
> > > It seems we should update base image we use to build go code after moving to new go version (for example I can see potential problem here https://github.com/lf-edge/eden/blob/master/Dockerfile, probably we can find other places with the same problem), can you please check?
> > 
> > 
> > I ran `make build-docker` , `make build` and `make install` all ran successfully. Is there any other way to verify this issue ?
> 
> It is `make build-docker`, sorry, it is not so obvious.

Thanks @giggsoff .

Yes, `make build-docker` was successful:
https://ctxt.io/2/AABQOoQeEA

**Comment by giggsoff** [comment]
> > > > It seems we should update base image we use to build go code after moving to new go version (for example I can see potential problem here https://github.com/lf-edge/eden/blob/master/Dockerfile, probably we can find other places with the same problem), can you please check?
> > > 
> > > 
> > > I ran `make build-docker` , `make build` and `make install` all ran successfully. Is there any other way to verify this issue ?
> > 
> > 
> > It is `make build-docker`, sorry, it is not so obvious.
> 
> Thanks @giggsoff .
> 
> Yes, `make build-docker` was successful: https://ctxt.io/2/AABQOoQeEA

Good to know, thank you!

One question so far: I still can see `github.com/golang/protobuf v1.5.2` in go.mod, can we avoid usage of the deprecated package? If it is not so easy, please do `go mod tidy` to indicate that we use the package indirectly.

**Comment by prnvkv-zededa** [comment]
> mod

You are right. Thanks, I addressed it.

**Review by giggsoff — APPROVED** [review]

**Comment by giggsoff** [comment]
It looks quite strange that all tests failed so early in the same place, will check a bit later

**Comment by giggsoff** [comment]
Well, seems I found the problem @prnvkv-zededa. Please use `cases.NoLower` option in all your `cases.Title` calls to work the same way as old `strings.Title` one.

**Comment by prnvkv-zededa** [comment]
> Well, seems I found the problem @prnvkv-zededa. Please use `cases.NoLower` option in all your `cases.Title` calls to work the same way as old `strings.Title` one.

Thanks @giggsoff ! 
Added the `cases.Nolower` option.

**Comment by giggsoff** [comment]
Can you please sign off your commits? I can see that [DCO](https://github.com/lf-edge/eden/pull/888/checks?check_run_id=15864115779) check failed.

**Pull request merged**
