### PR TITLE
bump up go version to 1.22 in setup-environment action

### PR DESCRIPTION
**Pull request by shjala**
missed this one in https://github.com/lf-edge/eden/pull/1012 .

### CODE REVIEW

**Comment by uncleDecart** [comment]
I grepped this things, did we got all the pokemons? 

```
.github/workflows/eden_setup.yml:27:          go-version: '1.20'
.github/workflows/eden_setup.yml:51:          go-version: '1.20'
.github/workflows/eden_gcp.yml:37:          go-version: '1.20'
.github/workflows/unit.yml:16:          go-version: '1.20'
.github/actions/setup-environment/action.yml:26:        go-version: '1.20'
```

**Comment by shjala** [comment]
> I grepped this things, did we got all the pokemons?
 damn you vscode search!

**Comment by shjala** [comment]
> I grepped this things, did we got all the pokemons?

@uncleDecart pull master and search again, poor vscode :D

**Comment by uncleDecart** [comment]
My apologies, that was old master indeed. LGTM

**Review by uncleDecart — APPROVED** [review]

**Pull request merged**
