### PR TITLE
log counting

### PR DESCRIPTION
**Pull request by giggsoff**
Add step for counting of logs

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Comment by giggsoff** [comment]
So, now we can see some information inside workflow output: https://github.com/lf-edge/eden/runs/2619751273?check_suite_focus=true#step:9:14
Also, I think, yetus problem is not fixable here.

**Comment by rvs** [comment]
Very nice @giggsoff -- you should demo it!

**Comment by mydatascience** [comment]
```
#!/bin/bash
echo "hello \
      from me"
```
Does this work? 

Else write a comment to ask yetus ignore some rules?

**Comment by giggsoff** [comment]
Added yamllint config with expand of max line length

**Pull request merged**
