### PR TITLE
remove deprecated freeUplink field

### PR DESCRIPTION
**Pull request by giggsoff**
We should remove deprecated freeUplink filed in favor of cost

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Comment by giggsoff** [comment]
@eriknordmark can you please take a look? Do we need to change cost anywhere?

**Comment by mydatascience** [comment]
this model zoo looks like a small hell... 
Maybe we may have some generator and database - or is it already somewhere?

**Review by eriknordmark — APPROVED** [review]
I don't understand how SetWiFiParams() is used hence whether it should set some cost where it sets freeUplink: false prior to your changes, Can you look into its usage?

Other than that it looks fine.

**Comment by giggsoff** [comment]
> this model zoo looks like a small hell...
> Maybe we may have some generator and database - or is it already somewhere?

Actually, it is an open source place to store them. We have generator inside EVE.

**Comment by giggsoff** [comment]
> I don't understand how SetWiFiParams() is used hence whether it should set some cost where it sets freeUplink: false prior to your changes, Can you look into its usage?

Actually, it is not so well and often used function.

**Pull request merged**
