### PR TITLE
bump docker/docker, oras and edge-container deps

### PR DESCRIPTION
**Pull request by deitch**
Supersedes #972

### CODE REVIEW

**Comment by deitch** [comment]
yetus is complaining about something that doesn't make sense.

**Review by giggsoff — APPROVED** [review]

**Comment by giggsoff** [comment]
> I would like to get this merged in. How do we handle the errors?

Looks like they are not related with your changes

**Comment by deitch** [comment]
Thanks @giggsoff ; so you are ok with merging?

**Comment by giggsoff** [comment]
> Thanks @giggsoff ; so you are ok with merging?

Yes, thank you for fixing dependency hell!

**Comment by deitch** [comment]
@giggsoff are you on lf-edge slack still?

**Pull request merged**
