### PR TITLE
[WIP] usb passthrough

### PR DESCRIPTION
**Pull request by giggsoff**
USB passthrough fixes 

For VM:
```
eden pod deploy -p 8027:22 https://cloud-images.ubuntu.com/releases/groovy/release-20201022.1/ubuntu-20.10-server-cloudimg-amd64.img  -v debug --metadata='#cloud-config\npassword: passw0rd\nlock_passwd: False\nchpasswd: { expire: False }\nssh_pwauth: True\n' --adapters USB2:2
```
For container-in-vm:
```
eden pod deploy -p 8027:22 docker://itmoeve/eclient:0.3 --adapters USB2:2
```

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Comment by giggsoff** [comment]
It works only for VM and container-in-VM, not for no-hyper containers (or for option without acceleration).

**Comment by sadov** [comment]
Test implementation:
https://github.com/itmo-eve/eden/tree/usb-pt-test

For the test, you need to run:
```
./dist/bin/qemu+usb.sh 
./dist/tests/eclient/eden+ports.sh 2223:2223 2224:2224
./eden test ./dist/tests/eclient -e usb-pt_test -v debug
```

**Comment by giggsoff** [comment]
Hi, @sadov. Can we do `eden eve stop` and `eden eve start` inside `qemu+usb.sh`? Or you suggest to restart only inside `eden+ports.sh`?

**Comment by sadov** [comment]
Hi @giggsoff. This time eden stop / start is commented out in qemu+usb.sh. For our workflow, we can use eden+ports.sh to restart after changing QEMU&EDEN configurations, because we need 2223,2224 ports for SSH redirection -- as in my example of test execution.

**Comment by giggsoff** [comment]
Please use `eden eve stop` and `eden eve start` not just `eden stop` and `eden start` inside `qemu+usb.sh`.
Another question: inside `eden+ports.sh` we restart only on change of ports, but if we already have 2223 and 2224 inside your sequence will not work.

**Comment by sadov** [comment]
This is a separate question about stopping/starting in test setup scripts -- maybe we need to do this explicitly in a workflow?

**Comment by giggsoff** [comment]
#474

**Pull request closed without merging**
