### PR TITLE
Revert "userdata: add tests for write_files in containers"

### PR DESCRIPTION
**Pull request by uncleDecart**
Reverts lf-edge/eden#918

Since there are failures on EVE master let's revert this test till we fix it 

cc:  @europaul  @milan-zededa @giggsoff

### CODE REVIEW

**Review by giggsoff — APPROVED** [review]
Let's stabilise other parts (moving to the new workflows of Eden itself) before pulling the test for new EVE-OS functionality.

**Comment by europaul** [comment]
@uncleDecart @giggsoff @milan-zededa can we include the test back since the supported EVE version was [bumped up](https://github.com/lf-edge/eden/commit/676412137346ee3d458c7bea3e6c7022848374d8) to 11.7.0, which includes the necessary EVE functionality?

**Comment by milan-zededa** [comment]
> @uncleDecart @giggsoff @milan-zededa can we include the test back since the supported EVE version was [bumped up](https://github.com/lf-edge/eden/commit/676412137346ee3d458c7bea3e6c7022848374d8) to 11.7.0, which includes the necessary EVE functionality?

Yes we can

**Comment by uncleDecart** [comment]
@europaul here's the PR https://github.com/lf-edge/eden/pull/941

**Pull request merged**
