### PR TITLE
Update IO perfomance test

### PR DESCRIPTION
**Pull request by vk-en**
Add env parameters for FIO to script for running test.

### CODE REVIEW

**Comment by giggsoff** [comment]
@vk-en now it runs with success: https://github.com/itmo-eve/eve-performance/tree/master/fio/FIO-tests-12-00-11-01-2021-0.0.0-master-79f610b8. Thank you.

**Comment by dkionka** [comment]
I think that this merge brought in several other changes that ended up changing a large number of files, and that is causing problems.

**Comment by dkionka** [comment]
Before approving a PR we need to verify that the commits are normal changes, not merges. New changes should be rebased before merging.

**Comment by dkionka** [comment]
The change from this PR is not causing the problem that I thought it was. The git history is nearly impossible to read now, but it ended up only changing 1 file.

**Comment by rvs** [comment]
> The change from this PR is not causing the problem that I thought it was. The git history is nearly impossible to read now, but it ended up only changing 1 file.

Are you suggesting we enable normalization of history on this repo?

**Comment by dkionka** [comment]
> > The change from this PR is not causing the problem that I thought it was. The git history is nearly impossible to read now, but it ended up only changing 1 file.
> 
> Are you suggesting we enable normalization of history on this repo?

Yes, you should change the way PRs are merged. It should default to squash or fast-forward. (I don't know if GitHub has some other "normalization" feature.) Use whatever Eve uses; its history is linear. Adam and Eden both have the unnecessarily complex merge histories.

**Pull request merged**
