### PR TITLE
Update the EVE API version.

### PR DESCRIPTION
**Pull request by OhmSpectator**
To AppInstanceConfig the following fields are added:
* Service - run app instance as a service container in the host/dom0
* CloudInitVersion - the version of the cloud-init config

To the Adapter config the following field is added:
* EthVf - the structure that describes information regarding Virtual Function

To the PhysicalIO config the following field is added:
* Vflist - list of Virtual Functions (VF) for given Physical Function (PF)

To storage types enum the following value is added:
* Target_AppCustom - for possible DTS usage

To the ContentTree config the following field is added:
* CustomMetaData - an arbitrary string, usage depends on the content purpose

To Volume config the following field is added:
* Target - рow the volume will be presented to the instance

To VmConfig the following field is added:
* PinCpu - set if the VM should run in a mode with pinned CPUs

To the physical IO types enum the following values are added:
* PhyIoType_PhyIoNetEthPF
* PhyIoType_PhyIoNetEthVF

To the application instance metadata types enum the following value is added:
* AppInstMetaDataType_APP_INST_META_DATA_TYPE_CUSTOM_STATUS To DeprecatedMetricItem the following field is added:
* VfInfo - information published for Virtual Function (VF) created by SR-IOV

Relates to https://github.com/lf-edge/eden/pull/829

### CODE REVIEW

**Review by giggsoff — COMMENTED** [review]
Please also update [version](https://github.com/lf-edge/eden/blob/master/pkg/defaults/defaults.go#L57) of Adam (as I can see it should be 0.0.42) we use to have all updates you mentioned.

**Comment by OhmSpectator** [comment]
Is it not a part of your PR https://github.com/lf-edge/eden/pull/829/files#diff-873ba6ea91d97fbdbd851e2af37c2dc38cdd079dedef667a3a9dca4f457ae7e9 ?
Or should we do it atomically?

**Comment by giggsoff** [comment]
Actually my PR contains both parts (api and adam update). But probably we should merge your changes and rebase my PR on top of yours to update only EVE-OS version there.

**Comment by OhmSpectator** [comment]
Then I have 2 questions.
How do I know the value of the `DefaultAdamTag` field? Where the 0.0.42 value comes from?
Should I update something else rather than `DefaultAdamTag`? What about `DeafultEVETag`?

**Comment by giggsoff** [comment]
> How do I know the value of the `DefaultAdamTag` field? Where the 0.0.42 value comes from?

You can find it here: https://hub.docker.com/r/lfedge/adam/tags. It comes from [run number](https://github.com/lf-edge/adam/blob/1a5193e894cce44aae9984d202de574c18054a19/.github/workflows/publish.yaml#L38) of [publish](https://github.com/lf-edge/adam/actions/runs/3628244829) workflow triggered by PR merge.

> Should I update something else rather than `DefaultAdamTag`? What about `DeafultEVETag`?

It depends. In general you should update `DefaultEVETag` as well to have EVE-OS support for new API. But now we do not have any functionality that use changes of API in Eden. And potentially we may have some issues with new EVE-OS version, we may try to solve during/before update of `DefaultEVETag` in separate PR (for example not all versions of EVE-OS have backward compatibility for our downgrade tests). In opposite, change of Adam/API is quite safe. So let's split update of `DefaultEVETag` into separate PR and concentrate on possible issues there.

**Comment by OhmSpectator** [comment]
Ok, thanks! Will add a commit with the Adam tag now.

**Comment by OhmSpectator** [comment]
Updated DefaultAdamTag.

**Pull request merged**
