### PR TITLE
Test arguments refactoring

### PR DESCRIPTION
**Pull request by sadov**
Passing standard Go-test parameters, via EDEN_TEST_ARGS env. var. Test params unification.

Signed-off-by: Oleg Sadov <oleg.sadov@gmail.com>

### CODE REVIEW

**Comment by sadov** [comment]
> Seems, that we have some [problems](http://eden-jenkins.fleandr.com:8080/job/Multi-Eden/16/console) with multiple Eden with this PR.

Fixed

**Comment by giggsoff** [comment]
Now it works, thank you.

**Comment by giggsoff** [comment]
Hi, @sadov! Seems, that with your rebases we have the same problem here: https://github.com/lf-edge/eden/blob/ca1621ef287c93ffa6383267acbc64a90916de2f/pkg/tests/functions.go#L85-L87

We must append to previously defined [tst.Env](https://github.com/lf-edge/eden/blob/master/pkg/tests/functions.go#L71-L72).

**Comment by sadov** [comment]
> eden/pkg/tests/functions.go

Fixed at: https://github.com/itmo-eve/eden/tree/test_args_fix

**Comment by giggsoff** [comment]
> > eden/pkg/tests/functions.go
> 
> Fixed at: https://github.com/itmo-eve/eden/tree/test_args_fix

Thank you, it works for me

**Pull request merged**
