### PR TITLE
Add CODEOWNERS file`

### PR DESCRIPTION
**Pull request by uncleDecart**
I sometimes miss PRs for eden, so I'm adding myself as code owner, so that I'll get notifications when somebody opens PR

cc: @eriknordmark

### CODE REVIEW

**Comment by milan-zededa** [comment]
Github allows to subscribe for all activity on the repository ;)

**Comment by uncleDecart** [comment]
That was lightning fast :D But that won't add me as reviewer on PR, would it?

**Comment by milan-zededa** [comment]
> That was lightning fast :D But that won't add me as reviewer on PR, would it?

No, but you will not miss anything.

**Comment by uncleDecart** [comment]
Fair @milan-zededa , but I think adding CODEOWNERS make sense to automatically assign PR on eden, right now it could be simple * pattern for now, but it's better to start early, than late. It is easier to add small things, than to try to fix big one

For instance, we can assign sdn on you, since you're the author :D And I can also add you under * pattern

**Pull request merged**
