### PR TITLE
build docker images and push them in release

### PR DESCRIPTION
**Pull request by giggsoff**
Add target to build all docker images from one place (make build-docker).
Add publish workflow to publish docker images on push into master.
Also, moves all images onto lfedge org:

- lfedge/eden
- lfedge/eden-eclient
- lfedge/eden-http-server
- lfedge/eden-fio-tests
- lfedge/eden-docker-test
- lfedge/eden-phoronix-test
- lfedge/eden-processing
- lfedge/eden-fledgeeveflirdemo

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Comment by rvs** [comment]
LGTM, but do you need LF Edge INFRA to create all these docker hub container image locations for you @giggsoff ?

**Comment by dautovri** [comment]
> LGTM, but do you need LF Edge INFRA to create all these docker hub container image locations for you @giggsoff ?

@rvs No need. We already texted to Linux foundation to inform them about that.

**Comment by rvs** [comment]
> @rvs No need. We already texted to Linux Foundation to inform them about that.

Ok @dautovri -- but when do you expect those to be created? I don't any of them available (yet?) on DockerHUB. Without that -- I don't think we can merge this PR.

**Comment by MightyNerdEric** [comment]
All of the repos have now been created in the lfedge namespace on Docker Hub.

**Comment by mydatascience** [comment]
why do we need so many images? Please add docs what is what...

**Comment by giggsoff** [comment]
> why do we need so many images? Please add docs what is what...

We already have all of them here, I didn’t add anything in this PR, just rename.

**Comment by giggsoff** [comment]
> why do we need so many images? Please add docs what is what...

I put docs in tests.

**Comment by rvs** [comment]
LGTM

**Pull request merged**
