### PR TITLE
lshw in debug container

### PR DESCRIPTION
**Pull request by giggsoff**
Add `eden utils debug hw <file>` command.

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Comment by rvs** [comment]
Why is this required @giggsoff ? And a follow up question -- if there's indeed a good reason of why this is required -- shouldn't it be part of EVE's debug package?

**Comment by giggsoff** [comment]
We will use it to provide HW info into results of performance tests. Actually, now we use [results](https://github.com/itmo-eve/eve-performance/blob/FIO-tests-06-29-22-12-2020-0.0.0-master-3021881c/FIO-tests-06-29-22-12-2020-0.0.0-master-3021881c/HARDWARE.cfg) from inside of VM (container-in-VM).

**Comment by rvs** [comment]
OK, so should we move it to EVE's debug package @giggsoff ?

**Comment by mydatascience** [comment]
Why do we need it in EVE? It is not used regularly. I'd say don't deploy to EVE something that is not daily used in production. P.S. Maybe we need to remove debug container from rootfs and with that take out  the problem of free space

**Pull request merged**
