### PR TITLE
First cut at allowing baseOS images to be loaded from OCI containers

### PR DESCRIPTION
**Pull request by rvs**
This is a rather ugly implementation that allows us to start implementing loading baseOS images from OCI containers, so that the following eden command `$ eden controller edge-node eveimage-update oci://docker.io/lfedge/eve:5.17.0-kvm` results in the following config given to EVE:

```
    "base": [
        {
            "uuidandversion": {
                "uuid": "a1cbf8a6-adda-4a24-9e95-18adf93060b6",
                "version": "4"
            },
            "drives": [
                {
                    "image": {
                        "uuidandversion": {
                            "uuid": "a1cbf8a6-adda-4a24-9e95-18adf93060b6",
                            "version": "1"
                        },
                        "name": "lfedge/eve:5.17.0-kvm",
                        "iformat": 8,
                        "dsId": "1a4acbf2-56bd-45ec-a2f4-c94dfc4cae35"
                    }
                }
            ],
            "baseOSVersion": "5.17.0-kvm"
        }
    ],
    "contentInfo": [
        {
            "uuid": "696a2b9a-f43d-4cf4-9bbd-32f1884b4218",
            "dsId": "1a4acbf2-56bd-45ec-a2f4-c94dfc4cae35",
            "URL": "lfedge/eve:5.17.0-kvm",
            "iformat": 8,
            "displayName": "lfedge/eve:5.17.0-kvm"
        }
    ],
    "volumes": [
        {
            "uuid": "f1b57261-82ee-47c1-aa28-645e8dad7712",
            "origin": {
                "type": 2,
                "downloadContentTreeID": "696a2b9a-f43d-4cf4-9bbd-32f1884b4218"
            },
            "displayName": "exciting_tesla_0_m_0"
        }
    ]
```

The config actually results in Image being fetched from Docker registry (great news) and then everything gets lost in the guts of baseOS update functionality and nothing useful happens.

Thus, I'd like to as @deitch to take a look at what's the deal on the EVE implementation side and also @giggsoff to suggest if there's a better approach compared to the totally hacky way I'm doing it now.

This is clearly NOT for merging (yet).

P.S. @eriknordmark -- you may also want to keep an eye on this since baseOS refactoring is expected to come to EVE soon.

### CODE REVIEW

**Comment by giggsoff** [comment]
Hi, @rvs. Could you explain the process of extracting the version from the given EVE image? 
Can the `docker run ... version` command be called? Or will some new image format be used in this case?

**Comment by mydatascience** [comment]
We need to update our eden test (update test) to test it

**Comment by deitch** [comment]
Here is why this doesn't work.

First of all, @rvs are you aware that your are creating it in _both_ `base` and in `contentInfo` in the config?

Separately, here is what happens:

1. The same image - defined as same relative url + same datastore ID - is placed in `contentInfo` and in `base`. They have distinct UUID.
1. in parallel:
    * zedagent sends the `contentInfo` image to volumemgr with tag `appImg.obj`
    * baseosmgr sends the `base` image to volumemgr with tag `baseOs.obj`
1. volumemgr receives both, for each:
    * sees that it does not have a latched tag (i.e. hash of the root)
    * checks for a `ResolveStatus`, does not find one. The lookup is comprised of `datastoreID+RelativeURL+Counter`, so the same for both images
    * creates a `ResolveConfig`. For the first one to arrive (normally the app one), it tries to resolve it. For the second, it publishes but pubsub sees a duplicate, so does nothing.
1. resolver (technically downloader) gets the response, publishes the `ResolveStatus`
1. volumemgr is subscribed to `ResolveStatus`, sees it. It then loops through all `ContentTree` that have that datastoreID+relativeURL, update it, publish, and run the core volumemgr loop `doUpdateContentTree`

The last step is the problem. It is [here](https://github.com/lf-edge/eve/blob/71d286e6fedbf41b795fbc463473ccb7d14493a6/pkg/pillar/cmd/volumemgr/handleresolve.go#L96-L122):

```go
func handleResolveStatusImpl(ctxArg interface{}, key string,
	statusArg interface{}) {

	log.Functionf("handleResolveStatusImpl for %s", key)
	ctx := ctxArg.(*volumemgrContext)
	rs := statusArg.(types.ResolveStatus)
	pub := ctx.pubContentTreeStatus
	items := pub.GetAll()
	for _, cs := range items {
		status := cs.(types.ContentTreeStatus)
		if !status.HasResolverRef ||
			status.RelativeURL != rs.Name ||
			status.DatastoreID != rs.DatastoreID {
			continue
		}
		log.Functionf("Updating SHA for content tree: %v",
			status.ContentID)
		changed, _ := doUpdateContentTree(ctx, &status)
		if changed {
			log.Functionf("ContentTree(Name:%s, UUID:%s): handleResolveStatusImpl status change.",
				status.DisplayName, status.ContentID)
			publishContentTreeStatus(ctx, &status)
		}
		updateVolumeStatusFromContentID(ctx, status.ContentID)
	}
	log.Functionf("handleResolveStatusImpl done for %s", key)
}
```

Notice the core loop of:

```go
	pub := ctx.pubContentTreeStatus
	items := pub.GetAll()
```

If you look at `pubContentTreeStatus`, the publication is defined [here](https://github.com/lf-edge/eve/blob/90d64f195e1074de73661c812b606488e92d0219/pkg/pillar/cmd/volumemgr/volumemgr.go#L183-L187):

```go
	pubContentTreeStatus, err := ps.NewPublication(pubsub.PublicationOptions{
		AgentName:  agentName,
		AgentScope: types.AppImgObj,
		TopicType:  types.ContentTreeStatus{},
	})
```

Note the agent scope is `types.AppImgObj`. So when the above routine loops through to update all of the ContentTreeStatus and kick off the loop, it misses it for the ContentTree from baseos.

Ouch.

I am surprised we still have that at all. We had decided months back that volumemgr was not going to look at that kind of scope at all; from the perspective of volumemgr, it wasn't going to care if it was an app image or baseos or etc.

I think @eriknordmark might know? 🤷‍♂️

**Comment by zed-rishabh** [comment]
@deitch I agree with you that it won't work in the current scenario but after API changes defined [here](https://github.com/lf-edge/eve/pull/1742), we will be able to clean up the content type (like ```types.AppImgObj```, ```types.BaseImgObj```) from the agent scope. ```zedagent``` will be the one who will publish the ```ContentTreeConfig``` to the volumemgr for both app images and base images. ```baseosmgr``` will publish the ```ContentTreeRefConfig``` to the ```volumemgr``` and in return, ```volumemgr``` will send the ```ContentTreeRefStatus``` to the ```baseosmgr```.
Like the way, ```zedmanager``` publishes the ```VolumeRefConfig``` to the volumemgr today.

**Comment by deitch** [comment]
@zed-rishabh that makes much more sense. 

So what is the way forward here? I think you are saying that this "ugly hack" (Roman's words) are not the way to go, and we should enable the API changes from 1742, get those working?

**Comment by zed-rishabh** [comment]
@deitch I think there is no harm if we add a new content tree config for baseos in device config because there is no pointer to the content tree config in ```base```. My only concern is why do we need volume config? I think the content tree config is enough for handling baseos.

**Comment by rvs** [comment]
We actually have to add both @deitch @zed-rishabh -- the long term plan here is to completely get rid of BaseOS stanza in the EVE config and simply use a special type of volume instead. We can do it now or we can do it later -- but the end game is Volume that has a property of being able to "boot into on raw hardware" is how we're going to handle BaseOS

**Comment by giggsoff** [comment]
The main question for me is `BaseOsVersion` field. We have the check inside EVE which compares [content](https://github.com/lf-edge/eve/blob/0a39965febc76eb13eb6aad643e9b0e18e224f34/pkg/pillar/zboot/zboot.go#L496-L504) of `/etc/eve-release` with this field. And I see inside `5.17.0-kvm-amd64`. So, we need to run `eden controller edge-node eveimage-update oci://docker.io/lfedge/eve:5.17.0-kvm-amd64` or add some logic which adds `amd64` if it not exists.

Another question: as I understand it, we are waiting for changes from EVE to support it? The generated config looks correct, but my attempt to update EVE this way was unsuccessful.

**Comment by deitch** [comment]
@giggsoff correct. I have been trying to get eve there via https://github.com/lf-edge/eve/pull/1751 but it needs more feedback on a suggested design change.

@rvs I don't think we need to have the content tree added twice - in baseos and in content trees - just baseos is enough.

**Comment by rvs** [comment]
> The main question for me is BaseOsVersion field. 

Right -- and I think we need to move to a much simpler approach there. See below.

> We have the check inside EVE which compares content of /etc/eve-release with this field. And I see inside 5.17.0-kvm amd64. So, we need to run eden controller edge-node eveimage-update oci://docker.io/lfedge/eve:5.17.0-kvm-amd64 or add some logic which adds amd64 if it not exists.

Right. So my proposal is that we simply trust the user. Worst that could happen an activation of a BaseOS image that doesn't match the version in the BaseOsVersion will fail and the use will get notified.

As you can see in this patch -- I scrubbed most of the mucking with the actual file -- and the version simply gets deduced from either a tag or a filename -- we can also add an explicit version option.

> Another question: as I understand it, we are waiting for changes from EVE to support it? The generated config looks correct, but my attempt to update EVE this way was unsuccessful.

Correct. That's what @deitch is working on. I suggest that once we agree on the above -- we actually merge this in so that he can finish his part of work.

Makes sense?

**Comment by rvs** [comment]
Hey @giggsoff @mydatascience -- please let me know if this looks like it can be merged

**Review by giggsoff — APPROVED** [review]
Yes, we can merge it. Thanks for the edits!

**Pull request merged**
