### PR TITLE
added new iEi TANK-870AI-i7 model

### PR DESCRIPTION
**Pull request by kgiori**
may need some phy label updates

### CODE REVIEW

**Comment by rvs** [comment]
Here's what I see with Yetus

> -1	patch	0m 2s		GH:672 does not apply to master. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help.

Given that GH seems the branch has no conflicts -- I'm wondering if @aw-was-here can help figuring out why Yetus is complaining

**Comment by rvs** [comment]
Oh, and @kgiori -- can you please add it to the README.md file here https://github.com/lf-edge/eden/blob/master/models/README.md

**Comment by aw-was-here** [comment]
```
git apply --binary -v --check -p1 /github/workspace/out/input.patch
Checking patch models/template_l1_rpi4-2G.json...
error: models/template_l1_rpi4-2G.json: already exists in working directory
Checking patch models/template_l1_rpi4-4G.json...
error: models/template_l1_rpi4-4G.json: already exists in working directory
Checking patch models/template_l1_rpi4-8G.json...
error: models/template_l1_rpi4-8G.json: already exists in working directory
Checking patch models/logo_back_TANK-870AI.png...
Checking patch models/logo_front_TANK-870AI.png...
Checking patch models/template_l1_iEi_TANK-870-AI-i7-8G-2A.json...
Checking patch models/template_l1_iEi_TANK-870-AI-i7-8G-2A.json...
```

Try a rebase+squash. Github interleaves commits, yetus does not.

**Comment by rvs** [comment]
Aha! @aw-was-here -- that makes sense! Thanks!

**Comment by kgiori** [comment]
included the new TANK model variant in the README and put it under iEi section instead of Intel

**Review by rvs — APPROVED** [review]
LGTM

**Pull request merged**
